name: Publish NPM Action
on:
  push:
    branches:
      - master
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Installing NodeJS...
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm run test
      - run: npm run clean && npm run build:typescript
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
